
import { ThemeProvider } from "next-themes";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <section
        className={`antialiased`}
      >
     
              <ThemeProvider>
                {children}
              </ThemeProvider>
            
      </section>
    </>
  );
}
